### ISSUE TITLE
Create Docker Compose definition

### ISSUE THREAD

**Issue by cosmocracy** [jvstein/docker-pybossa#1]
Having a `docker-compose.yml` file as part of the project would make it even easier to spin up Pybossa and the supporting database/redis server.  I would be happy to fork and submit a PR if you have interest.

**Comment by jvstein** [comment]
I keep mine in a separate repo.

https://github.com/jvstein/docker-compose-pybossa

**Comment by cosmocracy** [comment]
Awesome, thank you!
